name: Build SM64 Vanilla for R36S

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-mips-linux-gnu libsdl2-dev

      - name: Build Game
        run: |
          make VERSION=eu GRAPHICS=gles2 WINDOW_BACKEND=sdl2 HIGH_FPS=1 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sm64-r36s-vanilla
          path: build/eu_pc/sm64.eu
